name: InvestorIntel.Ai Testing

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
        pip install fastapi httpx pytest-mock
        
    - name: Create mock environment variables for testing
      run: |
        echo "AWS_ACCESS_KEY_ID=dummy" >> .env
        echo "AWS_SECRET_ACCESS_KEY=dummy" >> .env
        echo "AWS_S3_BUCKET_NAME=dummy" >> .env
        echo "AWS_REGION=us-east-1" >> .env
        echo "GEMINI_API_KEY=dummy" >> .env
        echo "PINECONE_API_KEY=dummy" >> .env
        echo "SNOWFLAKE_USER=dummy" >> .env
        echo "SNOWFLAKE_PASSWORD=dummy" >> .env
        echo "SNOWFLAKE_ACCOUNT=dummy" >> .env
        echo "SNOWFLAKE_WAREHOUSE=dummy" >> .env
        echo "SNOWFLAKE_DATABASE=INVESTOR_INTEL_DB" >> .env
        echo "SNOWFLAKE_ROLE=dummy" >> .env
      
    - name: Run tests
      run: |
        pytest tests/ -v
      
    - name: Run test coverage
      run: |
        pytest tests/ --cov=backend --cov-report=xml
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        
    - name: Lint with flake8
      run: |
        flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics
        
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit
        
    - name: Run Bandit security scanner
      run: |
        bandit -r backend/ -f json -o bandit-results.json || true
        
    - name: Upload security scan results
      uses: actions/upload-artifact@v3
      with:
        name: security-scan-results
        path: bandit-results.json
